### ISSUE TITLE
Pi High Quality Camera Adaptor File - Corrupt

### ISSUE THREAD

**Issue by isaac7437** [PiSupply/3D-Print#2]
Hello, the file '_Pi High Quality Camera Adaptor_' doesn't seem to be working properly, I cannot open the file in Cura, PrusaSlicer and Windows 3D Builder/Viewer.

Could you upload a working file?

Thanks, Isaac.

**Comment by ryanteck** [comment]
Hi @ChristopherRush did you design this part?

**Comment by Paramojo** [comment]
Hi @ChristopherRush @shawaj  yup after this part myself, and found it to be corrupt. Is it listed to download anywhere else?

**Comment by ChristopherRush** [comment]
Yes, I'll try and dig out the file and share it.

**Comment by ryanteck** [comment]
Thanks @ChristopherRush , much appreciated.

**Comment by isaac7437** [comment]
Thanks, @ChristopherRush. 🙂

**Comment by isaac7437** [comment]
Hi @ChristopherRush do you have a update?

Thanks.

**Comment by ChristopherRush** [comment]
@isaac7437 Please try this here - https://drive.google.com/file/d/1SDDEP5BVz6VshZE2wNz1ZXEZagCh1HZB/view?usp=sharing Any problem please let me know. Thanks.

**Comment by isaac7437** [comment]
> @isaac7437 Please try this here - https://drive.google.com/file/d/1SDDEP5BVz6VshZE2wNz1ZXEZagCh1HZB/view?usp=sharing Any problem please let me know. Thanks.

@ChristopherRush - Thanks! I'm closing this issue now.

**Comment by shawaj** [comment]
Here is the file for future reference
[Amazing Amberis-6.stl.zip](https://github.com/PiSupply/3D-Print/files/6141825/Amazing.Amberis-6.stl.zip)
